name: portfolio
description: "A professional Flutter portfolio website"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # URL Launcher for opening links and downloads
  url_launcher: ^6.3.1
  animated_text_kit: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Uncomment to add your assets
  # assets:
  #   - assets/images/
  #   - assets/resume.pdf