name: portfolio
description: "A professional Flutter portfolio website"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1
  animated_text_kit: ^4.3.0
  dio: ^5.3.2
  path_provider: ^2.1.1
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/resume/AnjanaMFlutterDev.pdf

  fonts:
    - family: Lexend
      fonts:
        - asset: fonts/Lexend-Regular.ttf
        - asset: fonts/Lexend-SemiBold.ttf
          weight: 600
        - asset: fonts/Lexend-Bold.ttf
          weight: 700